### ISSUE TITLE
`python setup.py test` fails

### ISSUE THREAD

**Issue by birdsarah** [mozilla/taar#74]
```
(taar) {13:33}~/Dev/mozilla/taar:crankycoder-features/issue-65 ✓ ➭ python setup.py test
zip_safe flag not set; analyzing archive contents...

Installed /home/bird/Dev/mozilla/taar/.eggs/pytest_runner-4.0-py2.7.egg
Searching for setuptools_scm
Reading https://pypi.python.org/simple/setuptools_scm/
Downloading https://pypi.python.org/packages/76/6e/3ba3d9c3409af4375b6c4512f78423381e9ed99375e7791586189207ea6a/setuptools_scm-1.15.7-py2.7.egg#md5=4385ebde52ea23f85fb490acb902095e
Best match: setuptools-scm 1.15.7
Processing setuptools_scm-1.15.7-py2.7.egg
Moving setuptools_scm-1.15.7-py2.7.egg to /home/bird/Dev/mozilla/taar/.eggs

Installed /home/bird/Dev/mozilla/taar/.eggs/setuptools_scm-1.15.7-py2.7.egg
running pytest
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    zip_safe=False,
  File "/home/bird/miniconda3/envs/taar/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/bird/miniconda3/envs/taar/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/bird/miniconda3/envs/taar/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/ptr.py", line 157, in run
  File "build/bdist.linux-x86_64/egg/ptr.py", line 118, in install_dists
AttributeError: class test has no attribute 'install_dists'
```

This was run on py2.7

**Comment by crankycoder** [comment]
This seems to work for me now - I'm not sure which particular commit closed this off.
